feat(apps): bunch of new apps
LGUG2Z/komorebi-application-specific-configuration pull request #42
Opened 2023-09-22 00:24 UTC by H4M5TER

- [x] I have formatted `applications.yaml` with `komorebic fmt-asc`.

2023-09-22 04:01 UTC, sitiom requested changes
I have applied some of my suggestions. Note that we only float fixed-size windows (which won't get appropriately managed with the tiling layout), so I have removed those unnecessary rules. Please see the rest of the comments.

2023-09-22 04:14 UTC, sitiom requested changes

2023-09-22 04:14 UTC, sitiom commented on applications.yaml
> +    comment: Friend list in Chinese
```suggestion
```

2023-09-22 04:27 UTC, sitiom commented on applications.yaml
> +    comment: Menu bar popup
```suggestion
```

2023-09-22 04:29 UTC, sitiom approved these changes

2023-09-22 04:30 UTC, merged

2023-09-23 11:00 UTC, H4M5TER commented
Thank you for your review
Let me explain the questions
1. Floating rules. The others is personal but for CopyQ it's a clipboard software when intented to pop up and disappear again. I'm sure most people don't want its position to be change by komorebi.
2. ManicTime. Is there a way to make ManicTime managed by komorebi?
3. OBS. 
3.1 Menu bar pop up is important. When you click the menu bar the pop up will appear (red rectangle). It will disrupt the layout without the floating rule.
![image](https://github.com/LGUG2Z/komorebi-application-specific-configuration/assets/21092951/5d78b0a4-a90f-4e41-aeb8-28566f708098)
3.2 `设置` actually means `Settings`. According to your explanation, OBS's settings is not fixed sized so just delete it.

2023-09-23 11:18 UTC, H4M5TER commented
I have made #43

2023-09-24 02:45 UTC, sitiom commented
> 1. Floating rules. The others is personal but for CopyQ it's a clipboard software which intended to pop up and disappear again. I'm sure most people don't want its position to be change by komorebi.

I used to use CopyQ on Linux. The way I use it is that I toggle the tray popup (which is not managed by the tiling wm) instead of the main window. By default, that should cover most use cases. If you want to float the main window, you pass your own `overrides.yaml` containing the rule.

> 2\. ManicTime. Is there a way to make ManicTime managed by komorebi?

Upon testing, yes: https://github.com/LGUG2Z/komorebi-application-specific-configuration/commit/88bbbe25130bdefa2a312762312f444ff5ceea05

> 3\. 3.1 Menu bar pop up is important. When you click the menu bar the pop up will appear (red rectangle). It will disrupt the layout without the floating rule.

It works just fine for me without the rule.

> 4\. Border overflow. Can you explain what the border overflow option means for me? I'm not sure about that.

Some apps (most notably Electron apps) have borders that overflow beyond the layout area and cover the gap space around it. Here's an example:

Without the rule:
![image](https://github.com/LGUG2Z/komorebi-application-specific-configuration/assets/56180050/9ffb8504-516a-48cd-a733-08c3633d6b83)
With the rule:
![image](https://github.com/LGUG2Z/komorebi-application-specific-configuration/assets/56180050/bc56e03e-1763-4fc1-88ac-1d119aa03819)

> 5\. Everything. I have two screen which is zoomed differently. When the Everything window is on the part of main screen which is next to another screen, it will be zoomed incorrectly. With border overflow option it works fine.

Can you elaborate more? Do you mean when Everything is between the two screens?

2023-09-24 06:33 UTC, H4M5TER commented
good case when window on left
![c817fc03c0dd680d763de69c4650583d](https://github.com/LGUG2Z/komorebi-application-specific-configuration/assets/21092951/e279d06e-2f07-4954-b4f7-0752bcfeaf6f)

good case when window on right with border overflow option
![3a69298a12e5d87123826b91a1cb32c7](https://github.com/LGUG2Z/komorebi-application-specific-configuration/assets/21092951/1af9b24b-17e5-4f8c-a323-fd5e4849e2b3)

bad case when window on right without option
![45b5534e5db7816daac7130fa32c3689](https://github.com/LGUG2Z/komorebi-application-specific-configuration/assets/21092951/624203aa-2837-41a2-824d-32e759bb6c95)

2023-09-24 06:39 UTC, H4M5TER commented
You are right. I can't reproduce the OBS issue. 
Can you explain more about how the `overrides.yml` works?

2023-09-24 06:48 UTC, sitiom commented
Window extending from the first screen to the second screen? I also have two screens with different zoom sizes, and I can't seem to replicate this. @LGUG2Z A bug from komorebi perhaps?

> You are right. I can't reproduce the OBS issue.
> Can you explain more about how the `overrides.yml` works?

If you are using a static configuration, you can define your own rules directly in the `komorebi.json`

![image](https://github.com/LGUG2Z/komorebi-application-specific-configuration/assets/56180050/386b79c1-36c6-4238-ac96-449c015f971e)

Alternatively, if you use an AutoHotkey config, you can run the `ahk-app-specific-configuration` or `ahk-asc` command to generate the script for the rules:
```
komorebic ahk-asc applications.yaml overrides.yaml
```